"use client";

import { Clock, Calendar, BookOpen } from "lucide-react";
import PhaseCard from "./PhaseCard";
import DownloadPDF from "./DownloadPDF";
import type { Roadmap } from "@/types/roadmap";

export default function RoadmapTimeline({ roadmap }: { roadmap: Roadmap }) {
  return (
    <div className="w-full overflow-hidden">
      <div className="mb-8">
        <h1 className="text-2xl sm:text-3xl font-bold text-white mb-2">
          {roadmap.title}
        </h1>
        <p className="text-gray-500 text-sm sm:text-base mb-4">{roadmap.description}</p>
        <div className="flex flex-wrap items-center gap-2 sm:gap-3">
          <div className="flex items-center gap-1.5 text-xs text-purple-400 bg-purple-500/10 px-2.5 py-1 rounded-full border border-purple-500/15">
            <Clock className="w-3 h-3" />
            <span>{roadmap.totalEstimatedTime}</span>
          </div>
          <div className="flex items-center gap-1.5 text-xs text-blue-400 bg-blue-500/10 px-2.5 py-1 rounded-full border border-blue-500/15">
            <Calendar className="w-3 h-3" />
            <span>{roadmap.phases.length} Phases</span>
          </div>
          <div className="flex items-center gap-1.5 text-xs text-green-400 bg-green-500/10 px-2.5 py-1 rounded-full border border-green-500/15">
            <BookOpen className="w-3 h-3" />
            <span>
              {roadmap.phases.reduce((acc, phase) => acc + phase.steps.length, 0)} Steps
            </span>
          </div>
          <DownloadPDF roadmap={roadmap} />
        </div>
      </div>

      <div className="space-y-2">
        {roadmap.phases.map((phase, index) => (
          <PhaseCard key={phase.id} phase={phase} index={index} />
        ))}
      </div>

      <div className="mt-10 pt-6 border-t border-white/5 text-center">
        <p className="text-xs text-gray-600">
          Generated by RoadmapAI
        </p>
      </div>
    </div>
  );
}
